### ISSUE TITLE
ofxSVGExtra:loadFromString missing external symbols in Visual Studio 2019 using of_0.12

### ISSUE THREAD

**Issue by Vamoss** [sebleedelisle/ofxLaser#47]
Hi,

I am attempting to compile in Visual Studio 2019 using of_0.12 and got these erros about `ofxSVGExtra:loadFromString missing external symbols`.

```
Severity	Code	Description																																																		Project File	Line	Suppression Status
Erro		MSB6006	"link.exe" was closed with code 1120.																																															PROJECT_NAME	C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets	1074	
Erro		LNK2019	unresolved external symbol, svgtiny_create, referenced in the function "public: void __cdecl ofxSVGExtra::loadFromString(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >)" (?loadFromString@ofxSVGExtra@@QEAAXV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@0@Z)	PROJECT_NAME	MY_PATH\of_v0.12.0_vs_release\apps\myApps\PROJECT_NAME\ofxSvgExtra.obj	1	
Erro		LNK2019	unresolved external symbol, svgtiny_parse, referenced in the function "public: void __cdecl ofxSVGExtra::loadFromString(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >)" (?loadFromString@ofxSVGExtra@@QEAAXV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@0@Z)		PROJECT_NAME	MY_PATH\of_v0.12.0_vs_release\apps\myApps\PROJECT_NAME\ofxSvgExtra.obj	1	
Erro		LNK2019	unresolved external symbol, svgtiny_free, referenced in the function "public: void __cdecl ofxSVGExtra::loadFromString(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >)" (?loadFromString@ofxSVGExtra@@QEAAXV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@0@Z)		PROJECT_NAME	MY_PATH\of_v0.12.0_vs_release\apps\myApps\PROJECT_NAME\ofxSvgExtra.obj	1	
Erro		LNK1120	3 unresolved external																																																	PROJECT_NAME	MY_PATH\of_v0.12.0_vs_release\apps\myApps\PROJECT_NAME\bin\PROJECT_NAME_debug.exe	1	

```

Is it possible to compile in this enviroment or do you recommend working in of_0.11?

**Comment by sebleedelisle** [comment]
Can you try adding the ofxSvg add-on? It seems like svgtiny library isn't loading.

**Comment by Vamoss** [comment]
Sure, I will try later today. Thank you!

**Comment by Vamoss** [comment]
It worked, thank you!
